config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :users, only: [:index, :new, :show] do
    member do
      get 'credit_new', to:'users#credit_new'
      post 'credit_create', to:'users#credit_create'
      get 'credit_show', to:'users#credit_show'
      delete 'credit_destroy', to:'users#credit_destroy'
      get 'logout', to:'users#logout'
      get 'draft_list_show', to:'users#draft_list_show'
    end
    resources :destinations, only: [:index, :new, :create, :edit, :update] 
  end
  resources :logs, only: [:index] do
    collection do
      get 'login'
    end
  end
  resources :products ,only: [:new, :create, :show, :edit, :update, :index, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get 'credit_new', to:'products#credit_new'
      post 'credit_create', to:'products#credit_create'
      delete 'credit_destroy', to:'products#credit_destroy'
      get 'purchase'
    end
    collection do
      post 'pay'
      get 'purchased'
    end
    # :idなし
    collection do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
    # :idあり
    member do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
  end
  resources :tops, only: [:index, :new] do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  VALID_KATAKANA_REGEX = /[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+/

  validates :nickname,         presence: true, length: { maximum: 20 }
  validates :email,            presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,         presence: true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX }
  validates :birthday,         presence: true
  validates :first_name,       presence: true, length: { maximum: 35 }
  validates :last_name,        presence: true, length: { maximum: 35 } 
  validates :first_name_kana,  presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'は全角カタカナで入力して下さい'}
  validates :last_name_kana,   presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'は全角カタカナで入力して下さい'}

  has_one :destination,        dependent: :destroy
  has_one :credit_card,        dependent: :destroy
  has_one :sns_authentication, dependent: :destroy
  has_many :products
  has_many :comments,          dependent: :destroy
  has_many :favorites,         dependent: :destroy

  accepts_nested_attributes_for :destination
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
    @destination = Destination.new
    @user.build_destination
  end

  private
  
  def destination_params
    params.require(:destination).permit(
      :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :prefecture_id, :city,:block, :building, :phone_number
    ).merge(user_id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require "payjp"
  
  before_action :card_present, only:[:credit_new, :credit_show, :credit_destroy]
  before_action :set_api_key
  before_action :set_customer, only:[:credit_show]
  before_action :set_card_information, only:[:credit_show]
  before_action :take_card, only:[:credit_show]

  def index
  end

  def show
    if user_signed_in? && current_user.id ==  params[:id].to_i
      @user = User.find(params[:id])
      @destination = @user.destination
      @card = CreditCard.find_by(user_id: current_user.id)
    else
      redirect_to root_path
    end
  end

  ######################## ▼ 下書き関連 ▼ ########################
    # 情報表示
    def draft_list_show
      @drafts = Product.where(public_flag: '0', seller_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
    end
  ######################## ▲ 下書き関連 ▲ ########################

  ######################## ▼ クレジットカード関連 ▼ ########################
  # products_controllerにも記述あり
  
  # 新規作成
  def credit_new
    if @card.present?
      redirect_to action: "credit_show"
    else
      @card = CreditCard.new
    end
  end

  # 登録
  def credit_create
    customer = Payjp::Customer.create(card: params['payjp-token'], metadata: {user_id: current_user.id})
    @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to user_path(current_user)
    else
      redirect_to action: "credit_new"
    end
  end

  # 情報表示
  def credit_show
    if @card.blank?
      redirect_to action: "credit_new"
    end
    @user = current_user
    @card = CreditCard.find_by(user_id: current_user.id)
    @card_brand = @card_information.brand
    case @card_brand
    when "Visa"
      @card_src = "visa.png"
    when "MasterCard"
      @card_src = "mastercard.png"
    when "JCB"
      @card_src = "JCB.png"
    when "American Express"
      @card_src = "AmericanExpress.png"
    when "Diners Club"
      @card_src = "DinersClub.png"
    when "Discover"
      @card_src = "DISCOVER.png"
    end
  end

  # 削除
  def credit_destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "credit_new"
    else
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      if @card.delete
        redirect_to user_path, notice: "削除完了しました"
      else
        redirect_to user_path, alert: "削除できませんでした"
      end
    end
  end
  ######################## ▲ クレジットカード関連 ▲ ########################

  private

  def card_present
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.find_by(user_id: current_user.id).present?
  end

  def set_api_key
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
  end

  def set_customer
    @customer = Payjp::Customer.retrieve(@card.customer_id)
  end

  def set_card_information
    @card_information = @customer.cards.retrieve(@card.card_id)
  end

  def take_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end

  def logout
  end

end

app/views/users/_draft_list_show.html.haml
.draft
  .draft__main
    .draft__main__title
      下書き一覧
    - @drafts.each do |draft|
      .draft__main__list
        .draft__main__list__left
        - if draft.product_images[0].presence
          = image_tag "#{draft.product_images[0].image.url}", class:'draft__main__list__left__img'
        - else
          = image_tag "", class:'draft__main__list__left__img'
        .draft__main__list__right
          .draft__main__list__right__top
          - if draft.name.blank?
            = link_to "(タイトル未入力)", edit_product_path(draft) ,class: "draft__main__list__right__top__title"
          - else 
            = link_to draft.name, edit_product_path(draft) ,class: "draft__main__list__right__top__title"
          .draft__main__list__right__bottom
          ー
    = paginate @drafts

app/views/users/_main_draft_list_show.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "users/draft_list_show"

app/views/users/_mypage-bar.html.haml
.mypage-bar
  .mypage-bar__index
    .mypage-bar__index__user
      .mypage-bar__index__user__tittle
        = image_tag "member_photo_noimage_thumb.png", class: "mypage-bar__index__user__tittle__icon"
        %p.mypage-bar__index__user__icon__tittle__name
          Name
      .mypage-bar__index__user__list
        %h1.mypage-bar__index__user__list__notice
          お知らせ
        %h1.mypage-bar__index__user__list__todo
          やることリスト
      .mypage-bar__index__user__product
        = image_tag "hoge.png", class: "mypage-bar__index__user__product__image"
        %p.mypage-bar__index__user__product__text
          サバの水煮を購入しました。
        %i.fas.fa-chevron-right
      .mypage-bar__index__user__product
        = image_tag "hoge.png", class: "mypage-bar__index__user__product__image"
        %p.mypage-bar__index__user__product__text
          サバの水煮を購入しました。
        %i.fas.fa-chevron-right
      .mypage-bar__index__user__show
        %p.mypage-bar__index__user__show__display-btn
          一覧を見る
    .mypage-bar__index__buy
      %h1.mypage-bar__index__buy__tittle
        購入した商品
      .mypage-bar__index__buy__list
        %h1.mypage-bar__index__buy__list__doing
          取引中
        %h1.mypage-bar__index__buy__list__history
          過去の商品
      .mypage-bar__index__buy__product
        = image_tag "hoge.png", class: "mypage-bar__index__buy__product__image"
        %p.mypage-bar__index__buy__product__text
          サバの水煮を購入しました。受け取り評価をしてください。
        %i.fas.fa-chevron-right
      .mypage-bar__index__buy__product
        = image_tag "hoge.png", class: "mypage-bar__index__buy__product__image"
        %p.mypage-bar__index__buy__product__text
          サバの水煮を購入しました。受け取り評価をしてください。
        %i.fas.fa-chevron-right
      .mypage-bar__index__buy__show
        %p.mypage-bar__index__buy__show__display-btn
          一覧を見る

app/views/users/_side-bar.html.haml
.side-bar
  %h1
    メニュー
  .menu
    .menu__mypage
      =link_to "マイページ", user_path(current_user.id),class: "menu__mypage__link"
      %i.fas.fa-chevron-right
    .menu__product
      =link_to "出品する", new_product_path ,class: "menu__product__link"
      %i.fas.fa-chevron-right
    .menu__edit
      =link_to "下書き一覧", "#" ,class: "menu__edit__link"
      %i.fas.fa-chevron-right
    .menu__exhibition
      =link_to "出品した商品", "#" ,class: "menu__exhibition__link"
      %i.fas.fa-chevron-right
    .menu__buy
      =link_to "購入した商品", "#" ,class: "menu__buy__link"
      %i.fas.fa-chevron-right
  %h1
    設定
  .config
    .config__user
      =link_to "プロフィール編集", "#" ,class: "config__user__link"
      %i.fas.fa-chevron-right
    .config__destinations
      =link_to "発送元・お届け先住所登録", "#" ,class: "config__destinations__link"
      %i.fas.fa-chevron-right
    .config__card
      =link_to "クレジットカード登録", "#" ,class: "config__card__link"
      %i.fas.fa-chevron-right
    .config__logout
      =link_to "ログアウト", "#" ,class: "config__logout__link"
      %i.fas.fa-chevron-right

app/views/users/create.html.haml
.sign-up
  .sign-up__header
    = render "devise/sessions/header"
  .sign-up__main
    .sign-up__main__form
      .sign-up__main__form__index
        %p 会員登録完了
      .sign-up__main__form__notice
        %p ありがとうございます。
        %p 会員登録が完了しました。
      =link_to "FURIMAを始める", root_path

  .sign-up__footer
    = render "devise/sessions/footer"

app/views/users/credit.html.haml
.wrapper
  = render "shared/header"
  = render "mypage/main-credit"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"

app/views/users/credit_new.html.haml
.wrapper
  = render "shared/header"
  = render "mypage/main_credit_new"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"

app/views/users/credit_show.html.haml
.wrapper
  = render "shared/header"
  = render "mypage/main_credit_show"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"

app/views/users/draft_list_show.html.haml
.wrapper
  = render "shared/header"
  = render "users/main_draft_list_show"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"

app/views/users/index.html.haml
.sign-up
  .sign-up__header
    = render "devise/sessions/header"
  .sign-up__main
    .sign-up__main__form
      .sign-up__main__form__index
        新規会員登録
      .sign-up__main__form__login
        .sign-up__main__form__login__sns
          = link_to new_user_registration_path, class:"sign-up__main__form__login__sns__mail" do
            %i.fas.fa-envelope
            メールアドレスで登録
          = link_to "#" , class:"sign-up__main__form__login__sns__google" do
            %i.fab.fa-google
            Googleで登録
          = link_to "#", class:"sign-up__main__form__login__sns__facebook" do
            %i.fab.fa-facebook-square
            Facebookで登録
          = link_to "#", class:"sign-up__main__form__login__sns__apple" do
            %i.fab.fa-apple
            AppleIDで登録

        .sign-up__main__form__login__notice
          登録することで、利用規約とプライバシーポリシーに同意したものとみなされます

  .sign-up__footer
    = render "devise/sessions/footer"

app/views/users/logout.html.haml
.wrapper
  = render "shared/header"
  = render "mypage/logout-main"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"

app/views/users/new.html.haml
.sign-up
  .sign-up__header
    = render "devise/sessions/header"
  .sign-up__main
    .sign-up__main__form
      .sign-up__main__form__index
        %p 新規会員登録
      .sign-up__main__form__login
        .sign-up__main__form__login__sns
          = link_to "メールアドレスで登録", new_user_registration_path,class:"sign-up__main__form__login__sns__mail"
          = link_to "googleで登録", logs_path ,class:"sign-up__main__form__login__sns__google"
          = link_to "facebookで登録", "#" ,class:"sign-up__main__form__login__sns__facebook"
          = link_to "AppleIDで登録", "#" ,class:"sign-up__main__form__login__sns__apple"
        %p.sign-up__main__form__login__notice
          登録することで、利用規約とプライバシーポリシーに同意したものとみなされます

  .sign-up__footer
    = render "devise/sessions/footer"

app/views/users/show.html.haml
.wrapper
  = render "shared/header"
  = render "mypage/main"
  = render "shared/bottom-banner"
  = render "shared/footer"
  = render "shared/sell-btn"