config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :users, only: [:index, :new, :show] do
    member do
      get 'credit_new', to:'users#credit_new'
      post 'credit_create', to:'users#credit_create'
      get 'credit_show', to:'users#credit_show'
      delete 'credit_destroy', to:'users#credit_destroy'
      get 'logout', to:'users#logout'
      get 'draft_list_show', to:'users#draft_list_show'
    end
    resources :destinations, only: [:index, :new, :create, :edit, :update] 
  end
  resources :logs, only: [:index] do
    collection do
      get 'login'
    end
  end
  resources :products ,only: [:new, :create, :show, :edit, :update, :index, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get 'credit_new', to:'products#credit_new'
      post 'credit_create', to:'products#credit_create'
      delete 'credit_destroy', to:'products#credit_destroy'
      get 'purchase'
    end
    collection do
      post 'pay'
      get 'purchased'
    end
    # :idなし
    collection do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
    # :idあり
    member do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
  end
  resources :tops, only: [:index, :new] do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/views/shared/_bottom-banner.html.haml
.bottom-banner
  .bottom-banner__content
    %h2.bottom-banner__content__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.bottom-banner__content__text
      今すぐ無料ダウンロード！
    .bottom-banner__content__stores
      = link_to "#" , class: "bottom-banner__content__stores__store-btn" do
        = image_tag "app-store.svg" , class: "bottom-banner__content__stores__store-btn__app-store"
      = link_to "#" , class: "bottom-banner__content__stores__store-btn" do
        = image_tag "google-play.svg" , class: "bottom-banner__content__stores__store-btn__google-play"

app/views/shared/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contets__content
      %h2.footer__contents__content__heading FURIMAについて
      %ul.footer__contents__content__lists
        %li.footer__contents__content__lists__list
          =link_to "会社概要（運営会社）", "#"
        %li.footer__contents__content__lists__list
          =link_to "プライバシーポリシー", "#"
        %li.footer__contents__content__lists__list
          =link_to "FURIMA利用規約", "#"
        %li.footer__contents__content__lists__list
          =link_to "ポイントに関する特約", "#"

    %li.footer__contets__content
      %h2.footer__contents__content__heading FURIMAを見る
      %ul.footer__contents__content__lists
        %li.footer__contents__content__lists__list
          =link_to "カテゴリー一覧", "#"
        %li.footer__contents__content__lists__list
          =link_to "ブランド一覧", "#"

    %li.footer__contets__content
      %h2.footer__contents__content__heading FURIMAについて
      %ul.footer__contents__content__lists
        %li.footer__contents__content__lists__list
          =link_to "FURIMAガイド", "#"
        %li.footer__contents__content__lists__list
          =link_to "FURIMAロゴ利用ガイドライン", "#"
        %li.footer__contents__content__lists__list
          =link_to "お知らせ", "#"

  .footer__logo
    = image_tag 'logo-white.png', class: "footer__logo__image" , width: "160px" , height: "46px"
  %p.footer__copyright ©️ FURIMA 

app/views/shared/_header.html.haml
.header
  .header__inner
    .header__inner__top
      %h1.header__inner__top__logo
        = link_to root_path do
          = image_tag "logo.png" , class:"header__inner__top__logo__furima-logo"
      .header__inner__top__search
        = form_tag products_path, method: :get, class: "header__inner__top__search__form" do
          = text_field_tag :keyword, "", class: "header__inner__top__search__form__input", placeholder: "キーワードから探す"
          = button_tag type: "submit",class: "header__inner__top__search__form__button" do
            = image_tag "icon-search 1.png" , class:"header__inner__top__search__form__button__search-icon"
            
    .header__inner__nav.nav
      .nav__left
        %h1.nav__left__category
          %span.nav__left__category__title カテゴリー
          .nav__left__category__list
            .nav__left__category__list__parents
              - @parents.each do |parent|
                = link_to "#{parent.name}", "#", class: "parent_category",id: "#{parent.id}"
            .nav__left__category__list__children 
            .nav__left__category__list__grand-children
        %h1.nav__left__brand
          ブランド

      .nav__right
        - if user_signed_in?
          = link_to "マイページ" , user_path(current_user.id), class: "nav__right__login"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__right__signup"
        - else
          = link_to "ログイン" , new_user_session_path, class: "nav__right__login"
          = link_to "新規会員登録", users_path, class: "nav__right__signup"

app/views/shared/_sell-btn.html.haml
= link_to new_product_path do
  .sell-btn
    %span.sell-btn__text 出品する
    = image_tag "icon_camera.png", class: "sell-btn__icon"