config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :users, only: [:index, :new, :show] do
    member do
      get 'credit_new', to:'users#credit_new'
      post 'credit_create', to:'users#credit_create'
      get 'credit_show', to:'users#credit_show'
      delete 'credit_destroy', to:'users#credit_destroy'
      get 'logout', to:'users#logout'
      get 'draft_list_show', to:'users#draft_list_show'
    end
    resources :destinations, only: [:index, :new, :create, :edit, :update] 
  end
  resources :logs, only: [:index] do
    collection do
      get 'login'
    end
  end
  resources :products ,only: [:new, :create, :show, :edit, :update, :index, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get 'credit_new', to:'products#credit_new'
      post 'credit_create', to:'products#credit_create'
      delete 'credit_destroy', to:'products#credit_destroy'
      get 'purchase'
    end
    collection do
      post 'pay'
      get 'purchased'
    end
    # :idなし
    collection do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
    # :idあり
    member do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
  end
  resources :tops, only: [:index, :new] do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/_credit-create.html.haml
.form-wapper
  = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do

    .signup-card

    - if @user.credit_card.blank?
      .signup-card__main

        .signup-card__main__container
          .signup-card__main__container__head
            %p クレジットカード情報入力

          .signup-card__main__container__register-form

            -# カード番号 入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'credit-card', class:"icon"
              %label カード番号
              %span.form-require 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
            .signup-card__main__container__register-form__image
              .visa
                -# = image_tag "visa.png", class: "visa"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/visa.svg?3222000695")
              .mastercard
                -# = image_tag "mastercard.png", class: "mastercard"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/master-card.svg?3222000695")
              .SAISONcard
                -# = image_tag "SAISONcard.png", class: "SAISONcard"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/saison-card.svg?3222000695")
              .JCB
                -# = image_tag "JCB.png", class: "JCB"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/jcb.svg?3222000695")
              .AmericanExpress
                -# = image_tag "AmericanExpress.png", class: "AmericanExpress"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/american_express.svg?3222000695")
              .DinersClub
                -# = image_tag "DinersClub.png", class: "DinersClub"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?3222000695")
              .DISCOVER
                -# = image_tag "DISCOVER.png", class: "DISCOVER"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/discover.svg?3222000695")

            -# 有効期限 入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'stopwatch', class:"icon"
              %label 有効期限
              %span.form-require 必須

            .term
              %select{ name: "exp_month", type: "text", class: "input-term", id: "exp_month"}
                %option{ value: "1"} 01
                %option{ value: "2"} 02
                %option{ value: "3"} 03
                %option{ value: "4"} 04
                %option{ value: "5"} 05
                %option{ value: "6"} 06
                %option{ value: "7"} 07
                %option{ value: "8"} 08
                %option{ value: "9"} 09
                %option{ value: "10"}10
                %option{ value: "11"}11
                %option{ value: "12"}12
              %span.term-label 月

              %select{ name: "exp_year", type: "text", class: "input-term", id: "exp_year"}
                %option{ value: "2020"} 20
                %option{ value: "2021"} 21
                %option{ value: "2022"} 22
                %option{ value: "2023"} 23
                %option{ value: "2024"} 24
                %option{ value: "2025"} 25
                %option{ value: "2026"} 26
                %option{ value: "2027"} 27
                %option{ value: "2028"} 28
                %option{ value: "2029"} 29
                %option{ value: "2030"} 30
              %span.term-label 年

            -# セキュリティコード入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'key', class:"icon"
              %label セキュリティコード
              %span.form-require 必須
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"

            #card_token
            .signup-card__main__container__register-form__btn
            = submit_tag "登 録", class: "signup-card__main__container__register-form__btn", id: "token_submit"

    - else
      .confirmation
        .confirmation__main
          .confirmation__main__title
            クレジットカード情報
          .confirmation__main__info
            .confirmation__main__info__brand
              = image_tag "#{@card_src}", class: "confirmation__main__info__brand__img", alt: @card_brand
            .confirmation__main__info__numbers
              .number
                = "**** **** **** " + @customer_card.last4
              .expiration-date
                .expiration-date__label
                  有効期限
                .expiration-date__info
                  - exp_month = @customer_card.exp_month.to_s
                  - exp_year = @customer_card.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year

          .destroy__function
            .destroy__function__link
              = link_to user_path(current_user.id), method: :delete, class: "destroy__function__link__btn" do
                削除する

app/views/mypage/_credit-new.html.haml
.form-wapper
  = form_tag(new_credit_card_path, method: :post, id: 'charge-form',  name: "inputForm") do

    .signup-card

      .signup-card__main

        .signup-card__main__container
          .signup-card__main__container__head
            %p クレジットカード情報入力

          .signup-card__main__container__register-form

            -# カード番号 入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'credit-card', class:"icon"
              %label カード番号
              %span.form-require 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
            .signup-card__main__container__register-form__image
              .visa
                -# = image_tag "visa.png", class: "visa"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/visa.svg?3222000695")
              .mastercard
                -# = image_tag "mastercard.png", class: "mastercard"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/master-card.svg?3222000695")
              .SAISONcard
                -# = image_tag "SAISONcard.png", class: "SAISONcard"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/saison-card.svg?3222000695")
              .JCB
                -# = image_tag "JCB.png", class: "JCB"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/jcb.svg?3222000695")
              .AmericanExpress
                -# = image_tag "AmericanExpress.png", class: "AmericanExpress"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/american_express.svg?3222000695")
              .DinersClub
                -# = image_tag "DinersClub.png", class: "DinersClub"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?3222000695")
              .DISCOVER
                -# = image_tag "DISCOVER.png", class: "DISCOVER"
                %img( src="https://pcweb-assets.mercdn.net/assets/img/card/discover.svg?3222000695")

            -# 有効期限 入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'stopwatch', class:"icon"
              %label 有効期限
              %span.form-require 必須

            .term
              %select{ name: "exp_month", type: "text", class: "input-term", id: "exp_month"}
                %option{ value: "1"} 01
                %option{ value: "2"} 02
                %option{ value: "3"} 03
                %option{ value: "4"} 04
                %option{ value: "5"} 05
                %option{ value: "6"} 06
                %option{ value: "7"} 07
                %option{ value: "8"} 08
                %option{ value: "9"} 09
                %option{ value: "10"}10
                %option{ value: "11"}11
                %option{ value: "12"}12
              %span.term-label 月

              %select{ name: "exp_year", type: "text", class: "input-term", id: "exp_year"}
                %option{ value: "2020"} 20
                %option{ value: "2021"} 21
                %option{ value: "2022"} 22
                %option{ value: "2023"} 23
                %option{ value: "2024"} 24
                %option{ value: "2025"} 25
                %option{ value: "2026"} 26
                %option{ value: "2027"} 27
                %option{ value: "2028"} 28
                %option{ value: "2029"} 29
                %option{ value: "2030"} 30
              %span.term-label 年

            -# セキュリティコード入力フォーム
            .signup-card__main__container__register-form__label
              = icon 'fas', 'key', class:"icon"
              %label セキュリティコード
              %span.form-require 必須
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"

            #card_token
            .signup-card__main__container__register-form__btn
            = submit_tag "登 録", class: "signup-card__main__container__register-form__btn", id: "token_submit"

app/views/mypage/_credit-show.html.haml
.signup-card
  .confirmation
    .confirmation__main
      .confirmation__main__title
        クレジットカード情報
      .confirmation__main__info
        .confirmation__main__info__brand
          = image_tag "#{@card_src}", class: "confirmation__main__info__brand__img", alt: @card_brand
        .confirmation__main__info__numbers
          .number
            = "**** **** **** " + @customer_card.last4
          .expiration-date
            .expiration-date__label
              有効期限
            .expiration-date__info
              - exp_month = @customer_card.exp_month.to_s
              - exp_year = @customer_card.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year

      .destroy-btn
        = link_to credit_destroy_user_path(current_user.id), method: :delete, class: "destroy-btn" do
          削除する

app/views/mypage/_credit_show.html.haml
.confirmation
  .confirmation__main
    .confirmation__main__title
      クレジットカード情報
    .confirmation__main__info
      .confirmation__main__info__brand
        = image_tag "#{@card_src}", class: "confirmation__main__info__brand__img", alt: @card_brand
      .confirmation__main__info__numbers
        .number
          = "**** **** **** " + @card_information.last4
        .expiration-date
          .expiration-date__label
            有効期限
          .expiration-date__info
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
    .destroy-btn
      = link_to credit_destroy_user_path, method: :delete, class: "destroy-btn" do
        削除する

app/views/mypage/_logout-main.html.haml
.logout-main
  = render "mypage/side-bar"
  = render "mypage/logout-bar"

app/views/mypage/_main-credit-new.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "mypage/credit-new"

app/views/mypage/_main-credit-show.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "mypage/credit-show"

app/views/mypage/_main-credit.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "mypage/credit-create"

app/views/mypage/_main.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "mypage/mypage-bar"

app/views/mypage/_main_credit_show.html.haml
.mypage-main
  = render "mypage/side-bar"
  = render "mypage/credit_show"

app/views/mypage/_mypage-bar.html.haml
.mypage-bar
  .mypage-bar__index
    .mypage-bar__index__user
      .mypage-bar__index__user__title
        = image_tag "member_photo_noimage_thumb.png", class: "mypage-bar__index__user__title__icon"
        %p.mypage-bar__index__user__icon__title__name
          =@user.nickname
      .mypage-bar__index__user__list
        %h1.mypage-bar__index__user__list__notice
          お知らせ
        %h1.mypage-bar__index__user__list__todo
          やることリスト
      .mypage-bar__index__user__product
        = image_tag "hoge.png", class: "mypage-bar__index__user__product__image"
        %p.mypage-bar__index__user__product__text
          サバの水煮を購入しました。
        %i.fas.fa-chevron-right
      .mypage-bar__index__user__product
        = image_tag "hoge.png", class: "mypage-bar__index__user__product__image"
        %p.mypage-bar__index__user__product__text
          サバの水煮を購入しました。
        %i.fas.fa-chevron-right
      .mypage-bar__index__user__show
        %p.mypage-bar__index__user__show__display-btn
          一覧を見る
    .mypage-bar__index__buy
      %h1.mypage-bar__index__buy__title
        購入した商品
      .mypage-bar__index__buy__list
        %h1.mypage-bar__index__buy__list__doing
          取引中
        %h1.mypage-bar__index__buy__list__history
          過去の商品
      .mypage-bar__index__buy__product
        = image_tag "hoge.png", class: "mypage-bar__index__buy__product__image"
        %p.mypage-bar__index__buy__product__text
          サバの水煮を購入しました。受け取り評価をしてください。
        %i.fas.fa-chevron-right
      .mypage-bar__index__buy__product
        = image_tag "hoge.png", class: "mypage-bar__index__buy__product__image"
        %p.mypage-bar__index__buy__product__text
          サバの水煮を購入しました。受け取り評価をしてください。
        %i.fas.fa-chevron-right
      .mypage-bar__index__buy__show
        %p.mypage-bar__index__buy__show__display-btn
          一覧を見る

app/views/mypage/_mypage_banner.html.haml
.banner
  .banner__left メルカリ
  .banner__right マイページ

app/views/mypage/_mypage_header.html.haml
.header
  .header__inner
    .head_form
      = image_tag 'FURIMA_top.svg'
      %input.search_bar{placeholder: "何かお探しですか?" }
    .header__nav-box
      .header_left_box
        .header_left_box__seek  
        .header_left_box__brand
      .header_right_box
        .header_right_box__like_index
        .header_right_box__notice
        .header_right_box__todo
        .header_right_box__mypage
    

app/views/mypage/_side-bar.html.haml
.side-bar
  %h1
    メニュー
  .menu
    .menu__mypage
      =link_to "マイページ", user_path(current_user.id), class: "menu__mypage__link"
      %i.fas.fa-chevron-right
    .menu__product
      =link_to "出品する", new_product_path, class: "menu__product__link"
      %i.fas.fa-chevron-right
    .menu__edit
      =link_to "下書き一覧", draft_list_show_user_path(current_user.id), class: "menu__edit__link"
      %i.fas.fa-chevron-right
    .menu__exhibition
      =link_to "出品した商品", "#", class: "menu__exhibition__link"
      %i.fas.fa-chevron-right
    .menu__buy
      =link_to "購入した商品", "#", class: "menu__buy__link"
      %i.fas.fa-chevron-right
  %h1
    設定
  .config
    .config__user
      =link_to "プロフィール編集", "#", class: "config__user__link"
      %i.fas.fa-chevron-right
    .config__destinations
      -if current_user.destination.nil?
        =link_to "発送元・お届け先住所登録", new_user_destination_path(current_user.id), class: "config__destinations__link"
        %i.fas.fa-chevron-right
      -else
        =link_to "発送元・お届け先住所変更", edit_user_destination_path(current_user.id), class: "config__destinations__link"
        %i.fas.fa-chevron-right
    .config__card
      - if current_user.credit_card.blank?
        =link_to "クレジットカード登録", credit_new_user_path(current_user.id), class: "config__card__link"
        %i.fas.fa-chevron-right
      - else
        =link_to "クレジットカード確認", credit_show_user_path(current_user.id), class: "config__card__link"
        %i.fas.fa-chevron-right
    .config__logout
      =link_to "ログアウト", logout_user_path(current_user.id), class: "config__logout__link"
      %i.fas.fa-chevron-right