config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tops#index"
  resources :users, only: [:index, :new, :show] do
    member do
      get 'credit_new', to:'users#credit_new'
      post 'credit_create', to:'users#credit_create'
      get 'credit_show', to:'users#credit_show'
      delete 'credit_destroy', to:'users#credit_destroy'
      get 'logout', to:'users#logout'
      get 'draft_list_show', to:'users#draft_list_show'
    end
    resources :destinations, only: [:index, :new, :create, :edit, :update] 
  end
  resources :logs, only: [:index] do
    collection do
      get 'login'
    end
  end
  resources :products ,only: [:new, :create, :show, :edit, :update, :index, :destroy] do
    resources :comments, only: [:create, :destroy]
    member do
      get 'credit_new', to:'products#credit_new'
      post 'credit_create', to:'products#credit_create'
      delete 'credit_destroy', to:'products#credit_destroy'
      get 'purchase'
    end
    collection do
      post 'pay'
      get 'purchased'
    end
    # :idなし
    collection do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
    # :idあり
    member do
      get 'get_product_category_children', defaults: { format: 'json' }
      get 'get_product_category_grandchildren', defaults: { format: 'json' }
      get 'get_product_size', defaults: { format: 'json' }
    end
  end
  resources :tops, only: [:index, :new] do
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_header_category_children', defaults: { format: 'json' }
      get 'get_header_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :product_condition
  belongs_to_active_hash :postage_way
  belongs_to_active_hash :shipping_day
  belongs_to_active_hash :product_size
  has_many :product_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id', optional: true
  belongs_to :product_category, optional: true
  belongs_to :product_brand, optional: true
  accepts_nested_attributes_for :product_images, allow_destroy: true

  #各項目のバリデーション
  with_options presence:true, if: :isProductPublicable?  do |v|
    v.validates :name
    v.validates :price, numericality: {greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
    v.validates :description
    v.validates :product_category_id
    v.validates :product_condition_id
    v.validates :postage_way_id
    v.validates :shipping_day_id
    v.validates :prefecture_id
  end

  #文字数制限や価格のしきい値
  validates :name                 , length: { maximum: 40 }
  validates :description          , length: { maximum: 1000 }
  #画像枚数のバリデーション
  validates :product_images       , length: { maximum: 10}

  private
  
  def isProductPublicable?
    public_flag == 1
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require "payjp"

  before_action :set_product_category_parent, only: :new
  before_action :card_present, only:[:credit_new, :credit_destroy, :purchase]
  before_action :set_api_key
  before_action :set_customer, only:[:purchase]
  before_action :set_card_information, only:[:purchase]
  before_action :take_card, only:[:purchase, :pay, :credit_destroy]
  before_action :get_product, only: [:show, :destroy, :edit, :update, :credit_new, :credit_create, :credit_destroy, :purchase]
  before_action :authenticate_user!, only: :new
  before_action :set_product_category_parent, only: [:new, :create, :edit, :update]
  

  def index
    #検索ワードが存在するか否かで分岐
    if params[:keyword].present?
      @products = Product.all
      #検索文字を取得（空欄含む）
      @keyword = params[:keyword]
      #検索文字を空欄で区切ったものを変数split_keywordに代入
      split_keywords = params[:keyword].split(/[[:blank:]]+/).select(&:present?)
      #区切ったワード事に検索を行う。すべての条件を満たす商品のみ検索結果に引っかかる。
      split_keywords.each do |keyword|
        @products = @products.where("name LIKE ?", "%#{keyword}%")
      end
    else
      redirect_to root_path
    end

  end

  def new
    @product = Product.new
    @product.product_images.build
    @product_category_parents = ProductCategory.where(ancestry: nil)
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end
  
  def create
    @product = Product.new(product_params)
    @draft = Product.new(draft_params)
    # product_size_idが空欄の時はサイズなしと表示させる。
    if product_params[:product_size_id].blank?
      @product.product_size_id = "サイズなし"
    end
    # 出品と下書き保存で処理を分岐する
    if params[:commit] == "出品する"
      if @product.save
        redirect_to root_path
      else
        render :new
      end
    elsif params[:commit] == "下書きに保存"
      if @draft.save
        redirect_to root_path
      else
        render :new
      end
    # 開発者がデバッグできるようにelse処理はコンソールへメッセージを出力
    else
      puts "No expected submit button"
    end
  end

  def edit
    if @product.product_category.present?
      @product.product_category.root
      @category_child_array = @product.product_category.root.children
      if @product.product_category.root.indirects.present?
        @category_grandchild_array = @product.product_category.parent.children
      end
      if @product.product_size.present?
        @product_size = @product.product_size
      end
    end
    if @product.public_flag == 0 && @product.product_images[0] == nil
      @product.product_images.build
    end
  end

  def update
    unnecessary_size_array     = [14, 29, 44, 57, 63, 68, 79, 82, 150, 163, 178, 188, 210, 255, 260];

    if (product_params[:product_category_id]).present?
      #編集した商品の子カテゴリ情報を取得。ノードの深さによって孫カテゴリが存在しているかを判断する。
      if ProductCategory.find(product_params[:product_category_id]).depth == 1
        product_category_children = ProductCategory.find(product_params[:product_category_id]).ancestry
      else
        product_category_children = ProductCategory.find(product_params[:product_category_id]).parent.ancestry
      end
      #product_size_idを持っていて、サイズがないカテゴリだった場合、サイズidを削除する
      if unnecessary_size_array.include?(product_category_children) && product_params[:product_size_id].present?
        product_params[:product_size_id].chop!
      end
    end
    #削除したサイズidに"サイズなし"という文字列をいれる
    if product_params[:product_size_id].blank?
      @product.product_size_id = "サイズなし"
    end
    # 出品商品への変更と下書き保存の上書きで処理を分岐する
    if params[:commit] == "変更を適用する"
      if @product.update(product_params)
        redirect_to root_path
      else
        render :edit
      end
    elsif params[:commit] == "下書きを上書きして保存"
      if @product.update(draft_params)
        redirect_to root_path
      else
        render :edit
      end
    # 開発者がデバッグできるようにelse処理はコンソールへメッセージを出力
    else
      puts "No expected submit button"
    end
  end

  # 購入確認ページ
  def purchase
    if @card.present?
      @user = current_user
      @card_brand = @card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "MasterCard"
        @card_src = "mastercard.png"
      when "JCB"
        @card_src = "JCB.png"
      when "American Express"
        @card_src = "AmericanExpress.png"
      when "Diners Club"
        @card_src = "DinersClub.png"
      when "Discover"
        @card_src = "DISCOVER.png"
      end
    end
    if current_user.destination
      @destination = Destination.find_by(user_id: current_user.id)
    end
    @@buy_product = @product
  end

  ######################## ▼ クレジットカード関連 ▼ ########################
  # users_controllerにも記述あり

  # 新規作成
  def credit_new
    if @card.present?
      redirect_to action: "credit_show"
    else
      @card = CreditCard.new
    end
  end

  # 登録
  def credit_create
    customer = Payjp::Customer.create(card: params['payjp-token'], metadata: {user_id: current_user.id})
    @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to purchase_product_path(@product.id)
    else
      redirect_to action: "credit_new"
    end
  end

  # 削除
  def credit_destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "credit_new"
    else
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      if @card.delete
        redirect_to purchase_product_path(@product.id), notice: "削除完了しました"
      else
        redirect_to purchase_product_path(@product.id), alert: "削除できませんでした"
      end
    end
  end
  ######################## ▲ クレジットカード関連 ▲ ########################

  # 購入
  def pay
    @card = CreditCard.find_by(user_id: current_user.id)
    @destination = Destination.find_by(user_id: current_user.id)
    if @card.present? && @destination.present?
      charge = Payjp::Charge.create(
        amount: @@buy_product.price,
        customer: Payjp::Customer.retrieve(@card.customer_id),
        currency: 'jpy'
      )
      @@buy_product.update(buyer_id: current_user.id)
      redirect_to purchased_products_path
    else
      redirect_to purchase_product_path(@@buy_product.id)
    end
  end

  def purchased
  end
  
  def destroy
    if @product.seller_id == current_user.id && @product.destroy
      redirect_to root_path
    else
      redirect_to product_path(@product)
    end
  end

  # 親カテゴリーに紐づく子カテゴリーの配列を取得
  def get_product_category_children
    @product_category_children = ProductCategory.find(params[:product_category_parent_name]).children
  end

  # 子カテゴリーに紐づく孫カテゴリーの配列を取得
  def get_product_category_grandchildren
    @product_category_grandchildren = ProductCategory.find("#{params[:product_category_child_id]}").children
  end

  # サイズの配列を取得
  def get_product_size
    @product_sizes = ProductSize.find_all_by_group "#{params[:product_size_id]}"
  end

private

  # 親カテゴリーの配列を取得
  def set_product_category_parent  
    @product_category_parents = ProductCategory.where(ancestry: nil)
  end

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :product_category_id,
      :product_condition_id,
      :postage_way_id,
      :shipping_day_id,
      :product_brand_id,
      :product_size_id,
      :prefecture_id,
      product_images_attributes: [:image, :_destroy, :id]
    ).merge(seller_id: current_user.id).merge(public_flag: "1")
  end

  def draft_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :product_category_id,
      :product_condition_id,
      :postage_way_id,
      :shipping_day_id,
      :product_brand_id,
      :product_size_id,
      :prefecture_id,
      product_images_attributes: [:image, :_destroy, :id]
    ).merge(seller_id: current_user.id).merge(public_flag: "0")
  end

  def card_present
    @card = CreditCard.find_by(user_id: current_user.id) if CreditCard.find_by(user_id: current_user.id).present?
  end

  def set_api_key
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
  end

  def set_customer
    if @card.present?
      @customer = Payjp::Customer.retrieve(@card.customer_id)
    end
  end

  def set_card_information
    if @card.present?
      @card_information = @customer.cards.retrieve(@card.card_id)
    end
  end

  def take_card
    @card = CreditCard.find_by(user_id: current_user.id)
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')} 円"
  end
end

app/views/products/_footer_products.html.haml
%ul.putup__footer__list
  %li.putup__footer__list__left プライバシーポリシー
  %li.putup__footer__list__center FURIMA利用規約
  %li.putup__footer__list__right 特定商取引に関する表記
= link_to (image_tag"FURIMA_top.svg",class:"putup__footer__logo"),root_path

%p ©️FURIMA inc

app/views/products/_header_products.html.haml
= link_to (image_tag"FURIMA_top.svg",class:"putup__header__logo"),root_path

app/views/products/credit_new.html.haml
.form-wrapper
  = form_with url: credit_create_product_path, model: @card, local: true, html: {name: "inputForm"}, class: 'form-wrapper', id: 'charge-form' do |form|

    .signup-creditcard

      .signup-creditcard__header
        = render "devise/sessions/header"

      .signup-creditcard__main
        .signup-creditcard__main__container
          .signup-creditcard__main__container__head
            %p クレジットカード情報入力

          .signup-creditcard__main__container__register-form
            
            -# カード番号 入力フォーム
            .signup-creditcard__main__container__register-form__number
              .signup-creditcard__main__container__register-form__number__label
                = icon 'fas', 'credit-card', class: "creditcard-icon"
                %label カード番号
                %span.form-require 必須
              = text_field_tag "number", "", class: "creditcard-number", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
              .signup-creditcard__main__container__register-form__number__image
                .visa
                  = image_tag asset_path("visa.png"), size: "64x24"
                .mastercard
                  = image_tag asset_path("mastercard.png"), size: "32x24"
                .JCB
                  = image_tag asset_path("JCB.png"), size: "32x26"
                .AmericanExpress
                  = image_tag asset_path("AmericanExpress.png"), size: "24x24"
                .DinersClub
                  = image_tag asset_path("DinersClub.png"), size: "72x24"
                .DISCOVER
                  = image_tag asset_path("DISCOVER.png"), size: "32x24"

            -# 有効期限 入力フォーム
            .signup-creditcard__main__container__register-form__period
              .signup-creditcard__main__container__register-form__period__label
                = icon 'fas', 'stopwatch', class: "creditcard-icon"
                %label 有効期限
                %span.form-require 必須

            .term
              %select{ name: "exp_month", type: "text", class: "input-term", id: "exp_month"}
                %option{ value: "1"} 01
                %option{ value: "2"} 02
                %option{ value: "3"} 03
                %option{ value: "4"} 04
                %option{ value: "5"} 05
                %option{ value: "6"} 06
                %option{ value: "7"} 07
                %option{ value: "8"} 08
                %option{ value: "9"} 09
                %option{ value: "10"}10
                %option{ value: "11"}11
                %option{ value: "12"}12
              %span.term-label 月

              %select{ name: "exp_year", type: "text", class: "input-term", id: "exp_year"}
                %option{ value: "2020"} 20
                %option{ value: "2021"} 21
                %option{ value: "2022"} 22
                %option{ value: "2023"} 23
                %option{ value: "2024"} 24
                %option{ value: "2025"} 25
                %option{ value: "2026"} 26
                %option{ value: "2027"} 27
                %option{ value: "2028"} 28
                %option{ value: "2029"} 29
                %option{ value: "2030"} 30
              %span.term-label 年

            -# セキュリティコード入力フォーム
            .signup-creditcard__main__container__register-form__security
              .signup-creditcard__main__container__register-form__security__label
                = icon 'fas', 'key', class: "creditcard-icon"
                %label セキュリティコード
                %span.form-require 必須
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"

            #card_token
            .signup-creditcard__main__container__register-form__btn
            = submit_tag "登 録", class: "signup-card__main__container__register-form__btn", id: "token_submit"

      .signup-creditcard__footer
        = render "devise/sessions/footer"

app/views/products/purchase.html.haml
.form-wrapper
  = form_with url: pay_products_path, local: true, class: 'form-wrapper' do |form|

    .purchase
      .purchase__header
        = render "header_products"

      .purchase__main
        %h2.purchase__main__product-confirmation
          購入内容の確認

        .purchase__main__product-info
          .purchase__main__product-info__inner
            .purchase__main__product-info__inner__content
              %h3.purchase__main__product-info__inner__content__img
                = image_tag @product.product_images[0].image.url
              .purchase__main__product-info__inner__content__detail
                .purchase__main__product-info__inner__content__detail
                  %p.purchase__main__product-info__inner__content__detail__name
                    = @product.name
                  %p.purchase__main__product-info__inner__content__detail__price
                    %span
                      = converting_to_jpy(@product.price)
                    %span.purchase__main__product-info__inner__content__detail__price__tax
                      (税込)
                      %br/
                      = @product.postage_way_id

        .purchase__main__payment-info
          .purchase__main__payment-info__innner
            %form{:action => "#", class: "purchase__main__payment-info__innner__form", :method => "post"}
              .purchase__main__payment-info__innner__form__table
                .purchase__main__payment-info__innner__form__table__pay-label
                  支払い金額
                .purchase__main__payment-info__innner__form__table__pay-amount
                  = converting_to_jpy(@product.price)

              .purchase__main__payment-info__innner__form__user-info
                %h3.purchase__main__payment-info__innner__form__user-info__pay-method
                  支払い方法
                - if @card.blank?
                  %p.purchase__main__payment-info__innner__form__user-info__text
                    = link_to credit_new_product_path(@product.id), class: "purchase__main__payment-info__innner__form__user-info__text" do
                      = icon('fas', 'plus-circle')
                      登録してください
                - else
                  .purchase-confirmation
                    .purchase-confirmation__title
                      クレジットカード情報
                    .purchase-confirmation__info
                      .purchase-confirmation__info__brand
                        = image_tag "#{@card_src}", class: "purchase-confirmation__info__brand__img", alt: @card_brand
                      .purchase-confirmation__info__numbers
                        .purchase-confirmation__info__numbers__number
                          = "**** **** **** " + @card_information.last4
                        .purchase-confirmation__info__numbers__expiration-date
                          .purchase-confirmation__info__numbers__expiration-date__label
                            有効期限
                          .purchase-confirmation__info__numbers__expiration-date__info
                            - exp_month = @card_information.exp_month.to_s
                            - exp_year = @card_information.exp_year.to_s.slice(2,3)
                            = exp_month + " / " + exp_year
                    .purchase-confirmation__destroy-btn
                      = link_to credit_destroy_product_path, method: :delete, class: "purchase-confirmation__destroy-btn" do
                        削除する

              .purchase__main__payment-info__innner__form__user-info
                %h3.purchase__main__payment-info__innner__form__user-info__destination
                  配送先
                -if current_user.destination.nil?
                  %p.purchase__main__payment-info__innner__form__user-info__text
                    = link_to new_user_destination_path(current_user.id) , class: "purchase__main__payment-info__innner__form__user-info__text" do
                      = icon('fas', 'plus-circle')
                      登録してください
                -else
                  %p.purchase__main__payment-info__innner__form__user-info__text
                    ="#{@destination.city}#{@destination.block}#{@destination.building}"

              .purchase__main__payment-info__innner__form__submit
              = form.submit "購入する", class: "purchase__main__payment-info__innner__form__submit__submit-btn"

      .purchase__footer
        = render "footer_products"

app/views/products/purchased.html.haml
.purchased
  .purchased__header
    = render "devise/sessions/header"


  .purchased__container
    .purchased__container__head
      %p 購入が完了しました
    .purchased__container__transition
      .purchased__container__transition__top
        = link_to "トップページへ戻る", root_path, class: "purchased__transition__top"
      .purchased__container__transition__mypage
        = link_to "マイページへ戻る", user_path(current_user.id), class: "purchased__transition__mypage"


  .purchased__footer
    = render "devise/sessions/footer"

app/views/products/show.html.haml
.show
  .show__header
    = render "shared/header"

  .show__navbar
    %ul
      %li 
        = link_to root_path , class: "show_navbar-top" do
          FURIMA
      %li 
        = icon('fa', 'angle-right')
      %li 
        = @product.product_category.root.name
      %li
        = icon('fa', 'angle-right')
      %li
        = @product.product_category.parent.name
      %li
        = icon('fa', 'angle-right')
      %li 
        = @product.product_category.name
      %li
        = icon('fa', 'angle-right')
      %li.show__navbar--last
        = @product.name

  .show__main

    .show__main__product
      .show__main__product__content
        .show__main__product__content__information
          %h2.show__main__product__content__information__name
            = @product.name

          -# 編集・削除ボタン（現在のユーザーが出品者かどうかで場合分け）
          -if user_signed_in? && current_user.id == @product.seller_id
            %ul.show__main__product__content__information__btn
              %li
                = link_to "編集する", edit_product_path(@product), class: "show__main__product__content__information__btn--edit", method: :get
              %li
                = link_to "削除する", product_path(@product), class: "show__main__product__content__information__btn--delete", method: :delete
          -else

          .show__main__product__content__information__image
            .show__main__product__content__information__image__top
              .show__main__product__content__information__image__top__stage
                .show__main__product__content__information__image__top--list
                  - @product.product_images.each_with_index do |product_image,index|
                    - if index == 0
                      %div{class: "show__main__product__content__information__image__top--list__item" , data:{index: index}, style: "z-index:10;"}
                        =image_tag product_image.image.url
                    -else
                      %div{class: "show__main__product__content__information__image__top--list__item", data:{index: index}, style: "z-index:1;"}
                        =image_tag product_image.image.url

            .show__main__product__content__information__image__sub
              - @product.product_images.each_with_index do |product_image,index|
                %div{class: "show__main__product__content__information__image__sub--list", data:{index: index}}
                  = image_tag product_image.image.url, {class: "sub-image"}

            // 買い手がいたらSOLDOUTを付与
            -if @product.buyer_id.present?
              .show__main__product__content__information__image--soldout

          .show__main__product__content__information__price
            %span
              = converting_to_jpy(@product.price)
              
            .show__main__product__content__information__price__detail
              %span
                (税込)
              %span
                = @product.postage_way_id

          .show__main__product__content__information__introduction
            = @product.description

          .show__main__product__content__information__table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    = @product.seller.nickname
                %tr
                  %th
                    カテゴリー
                    -if @product.product_category.depth == 2
                      %td
                        = link_to "#", class: "show__main__product__content__information__table__category" do
                          = @product.product_category.root.name
                        %br/
                        = link_to "#", class: "show__main__product__content__information__table__category" do
                          = @product.product_category.parent.name
                        %br/
                        = link_to "#", class: "show__main__product__content__information__table__category" do
                          = @product.product_category.name
                    -else
                      %td
                        = link_to "#", class: "show__main__product__content__information__table__category" do
                          = @product.product_category.root.name
                        %br/
                        = link_to "#", class: "show__main__product__content__information__table__category" do
                          = @product.product_category.name
                %tr
                  %th
                    ブランド
                  %td
                    -# ブランド名があるかないかで場合分け
                    -if @product.product_brand != nil
                      = @product.product_brand.brand_name
                      
                    -else
                      
                %tr
                  %th
                    商品のサイズ
                  %td
                    -if @product.product_size.present?
                      = @product.product_size.name
                    - else
                      サイズなし
                %tr
                  %th
                    商品の状態
                  %td
                    = @product.product_condition_id
                %tr
                  %th
                    配送料の負担
                  %td
                    = @product.postage_way_id
                %tr
                  %th
                    発送元の地域
                  %td
                    = link_to "#", class: "show__main__product__content__information__table__derection" do
                      = @product.prefecture_id
                %tr
                  %th
                    発送日の目安
                  %td
                    = @product.shipping_day_id

          -# ユーザーが出品者かそうで無いかでボタン表示の場合分け
          - if user_signed_in? && current_user.id == @product.seller_id

          - else
            .show__main__product__content__information__option 
              %ul.show__main__product__content__information__option__btn
                %li.show__main__product__content__information__option__btn--favorite
                  = icon('fa', 'star')
                  お気に入り 0

              -# 商品が品切れかどうかで場合分け
              - if @product.buyer_id != nil
                %ul.show__main__product__content__information__option__btn
                  %li.show__main__product__content__information__option__btn--soldout
                    売り切れ中
              - else
                %ul.show__main__product__content__information__option__btn
                  %li.show__main__product__content__information__option__btn--purchase
                    -# ユーザーがログインしているか否かで場合分け
                    - if user_signed_in?
                      = link_to purchase_product_path(@product), class: "show__main__product__content__information__option__btn--purchase" do
                        購入画面に進む
                    - else 
                      = link_to new_user_session_path, class: "show__main__product__content__information__option__btn--purchase" do
                        購入には登録が必要です

              %ul.show__main__product__content__information__option__btn
                %li.show__main__product__content__information__option__btn--report
                  = link_to "#", class: "show__main__product__content__information__option__btn--report" do
                    = icon('fa', 'flag')
                    不適切な商品の通報

        .show__main__product__content__comment
          %ul.show__main__product__content__comment__text
            - if @comments
              - @comments.each do |comment| 
                %li.show__main__product__content__comment__text__list
                  .show__main__product__content__comment__text__list__name
                    = comment.user.nickname

                    -# 出品者のコメントの場合、出品者と分かるように表示
                    - if comment.user_id == @product.seller_id
                      %p.show__main__product__content__comment__text__list__name--seller
                        出品者
                    - else 

                    -# コメントした本人のみ削除ボタンを表示
                    -if user_signed_in? && current_user.id == comment.user_id
                      %ul.show__main__product__content__comment__text__list__btn
                        %li
                          = link_to "コメントを削除する", product_comment_path(comment.product.id, comment.id), class: "show__main__product__content__comment__text__list__btn--delete", method: :delete
                    -else

                  .show__main__product__content__comment__text__list__sentence
                    = comment.comment
                
          -# ユーザーがログインしているか否かでコメント投稿フォームの表示切り替え
          - if current_user
            = form_with(model: [@product, @comment], class: "show__main__product__content__comment__form", local: true, id: "new_comment") do |form|
              = form.text_area :comment, placeholder: "500文字まで入力可能です", maxlength: 500,  class: "show__main__product__content__comment__form__textbox"
              %p.show__main__product__content__comment__form__notice
                相手のことを考え丁寧なコメントを心がけましょう。
                %br/
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              = button_tag type: 'submit', class: "show__main__product__content__comment__form__submit" do
                = icon('fa', 'comment')
                コメントする

          - else 
            %p.show__main__product__content__comment__form__unlogin
              ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

      %ul.show__main__product__links 
        %li
          = link_to "#", class: "show__main__links__before" do
            = icon('fa', 'angle-left')
            前の商品
        %li 
          = link_to "#", class: "show__main__links__after" do
            後ろの商品
            = icon('fa', 'angle-right')

      .show__main__product__related
        = link_to "#", class: "show__main__product__related__items" do
          = @product.product_category.root.name
          をもっと見る
        %ul.show__main__product__related__lists
          %li.show__main__product__related__lists__list
            = link_to "#", class: ".show__main__product__related__lists__list" do
              .show__main__product__related__lists__list__img

              .show__main__product__related__lists__list__body
                %h3
                .show__main__product__related__lists__list__body__details
                  %ul
                    %li
                    %li
                      = icon('', '')
                  %p  

  .show__banner
    = render "shared/bottom-banner"

  .show__footer
    = render "shared/footer"